"""
Tamil Medical Glossary
Approved simple Tamil terminology for radiology reports.
"""

TAMIL_MEDICAL_GLOSSARY = {
    "disc": "டிஸ்க் (முதுகெலும்புகளுக்கு இடையிலான மெத்தை)",
    "disc bulge": "டிஸ்க் சற்று வெளியே தள்ளியிருத்தல்",
    "desiccation": "டிஸ்க் உலர்ந்திருத்தல்",
    "ligament": "தசைநார்",
    "cartilage": "குருத்தெலும்பு",
    "meniscus": "முழங்கால் மெத்தை (மெனிஸ்கஸ்)",
    "tear": "கிழிவு",
    "sprain": "சுளுக்கு",
    "joint": "மூட்டு",
    "joint effusion": "மூட்டில் நீர் கோர்த்திருத்தல்",
    "arthropathy": "மூட்டு தேய்மானம்",
    "arthritis": "மூட்டு தேய்மானம்",
    "nerve root": "நரம்பு வேர்",
    "thecal sac": "நரம்புகளைச் சுற்றியுள்ள உறை",
    "consolidation": "நுரையீரலின் ஒரு பகுதி அடர்த்தியாகத் தெரிதல்",
    "opacity": "நுரையீரலின் ஒரு பகுதி அடர்த்தியாகத் தெரிதல்",
    "costophrenic angle": "நுரையீரலின் கீழ் ஓரம்",
    "infection": "தொற்று",
    "inflammation": "அழற்சி",
    "fracture": "எலும்பு முறிவு",
    "lung": "நுரையீரல்",
    "kidney": "சிறுநீரகம்",
    "liver": "கல்லீரல்",
    "medial": "உள் பக்கம்",
    "lateral": "வெளிப் பக்கம்",
    "posterior": "பின் பகுதி",
    "anterior": "முன் பகுதி",
    "femur": "தொடை எலும்பு",
    "tibia": "கால் முன் எலும்பு",
    "fluid": "நீர்",
    "herniation": "டிஸ்க் வெளியே பிதுங்குதல்",
    "protrusion": "டிஸ்க் வெளியே பிதுங்குதல்",
    "collateral ligament": "பக்கவாட்டுத் தசைநார்",
    "thickening": "தடிப்பு",
    "blunting": "ஓரம் சற்று மழுங்கியிருத்தல்",
    "haemorrhage": "ரத்தக்கசிவு",
    "bleed": "ரத்தக்கசிவு",
    "stone": "கல்",
    "calculus": "கல்",
    "mass": "கட்டி போன்ற பகுதி",
    "lesion": "கட்டி போன்ற பகுதி",
    "biopsy": "திசு பரிசோதனை",
    "horn": "பின் பகுதி (never மூக்கு)",
    "femoral condyle": "தொடை எலும்பின் கீழ் முனை",
    "hydronephrosis": "சிறுநீரகத்தில் நீர் தேங்கி வீங்கியிருத்தல்",
}
