version: '3.8'

services:
  backend:
    build: ./backend
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
    volumes:
      - ./backend/app:/app/app
      - ./backend/nalamnet.db:/app/nalamnet.db

  frontend:
    build:
      context: ./frontend-xr
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
